[tool.ruff]
target-version = "py311"

select = ["ALL"]
ignore = ["D211", "D212", "ANN101", "ANN102", "ANN002", "ANN003", "SLF"]

fixable = ["ALL"]

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "venv",
    "*_test.py",
    "migrations",
]
per-file-ignores = {}

# Same as Black.
line-length = 99

[tool.ruff.pydocstyle]
convention = "google"


[tool.black]
line-length = 99
target-version = ['py311']

